### ISSUE TITLE
failed to collect filesystem stats

### ISSUE THREAD

**Issue by sampointer** [wavefrontHQ/cadvisor#3]
v0.25 with SHA `1cc0e9c400a0` logs the following:

```
E1212 16:02:35.351778 1 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: <nil>, rootInodeErr: cmd [find /rootfs/var/lib/docker/aufs/diff/7943acd31941fe762a940cae3e6e2ce88dd347e75f37ec89e9f0ee6c0a539c8c -xdev -printf .] failed. stderr: find: unrecognized: -printf
```

This is discussed in this ticket from the upstream project: https://github.com/google/cadvisor/issues/1556

Please do whatever is necessary to incorporate the fix into the most recent stable container image.

**Comment by vikramraman** [comment]
@sampointer Have you tried newer versions of cadvisor? The latest we have published is v0.29. https://hub.docker.com/r/wavefronthq/cadvisor/tags/
